config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'home#start'
  get 'home/top' => 'home#top'
  get 'home/ranking' => 'home#ranking'

  get 'search/search'
  get '/search', to: 'search#search'

  get 'post_items/complete' => 'post_items#complete', as: 'post_items_complete'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'users_unsubscribe'
  patch 'users/:id/withdraw' => 'users#withdraw', as: 'users_withdraw'
  put 'users/:id/withdraw' => 'users#withdraw'
  get '/thanks' => 'users#thanks', as: 'thanks'


  resources :post_items do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :genres, only: [:create, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :introduction, length: { maximum: 100 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_items, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorites_post_items, through: :favorites, source: :post_item
  attachment :profile_image

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  scope :only_valid, -> { where(is_valid: true) }

  enum is_valid: {"有効": true, "無効": false}

  def active_for_authentication?
    super && (self.is_valid === "有効")
  end

  def self.search_for(content, method)
    User.where('name LIKE ?', '%' + content + '%')
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.guest
    find_or_create_by!(name: 'ゲスト', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_inactive_user, only: [:create]




  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def reject_inactive_user
    @user = User.find_by(email: params[:user][:email])
    if @user
      if @user.valid_password?(params[:user][:password]) && !@user.is_valid
        redirect_to new_user_session_path, notice: 'お客様は退会済みです。申し訳ございませんが、別のメールアドレスをお使いください。'
      end
    end
  end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'ゲストユーザーとしてログインしました。'
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :unsubscribe, :withdraw]
  before_action :ensure_correct_user, only: [:edit, :update, :unsubscribe, :withdraw]

  def index
    @users = User.only_valid.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @favorites_count = 0
    @user.post_items.each do |post_item|
      @favorites_count += post_item.favorites.count
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: '会員情報の更新が完了しました。'
    else
      render :edit, alert: '会員情報の更新に失敗しました。'
    end
  end

  def unsubscribe
    @user = current_user
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.post_items.delete_all
    @user.post_comments.delete_all
    @user.update(is_valid: "無効")
    reset_session
    redirect_to thanks_path, notice: 'ご利用ありがとうございました。'
  end

  def thanks
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user), alert: "権限がございません。"
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<div class="users-index">
	<% users.each do |user| %>
		<div class="users-index-content">
			<%= link_to user_path(user) do %>
				<%= attachment_image_tag user, :profile_image, size:'250x250', fallback: "no_image_icon.jpg" %>
				<h3><%= user.name.truncate(16) %></h3>
			<% end %>
		</div>
	<% end %>
</div>

app/views/users/_search_index.html.erb
<div class="search-user-content">
	<% users.each do |user| %>
		<div class="search-user">
			<%= link_to user_path(user) do %>
				<%= attachment_image_tag user, :profile_image, size:'250x250', fallback: "no_image_icon.jpg" %>
				<h3><%= user.name.truncate(16) %></h3>
			<% end %>
		</div>
	<% end %>
</div>

app/views/users/edit.html.erb
<h1>登録情報変更</h1>

<%= form_with model:@user, local: true do |f| %>

<%= render 'layouts/error_messages', model: f.object %>

<div class="user-edit">
	<div class="user-edit-image">
		<h2><%= f.label "プロフィール画像" %></h2>
		<%= attachment_image_tag @user, :profile_image, id: "img_prev", size:'300x300', fallback: "no_image_icon.jpg" %></br>
		<%= f.attachment_field :profile_image, :placeholder =>"#{@user.profile_image}" %>
	</div>

	<div class="user-edit-form">
		<h2><%= f.label :name %></h2>
		<%= f.text_field :name %>

		<h2><%= f.label :email %></h2>
		<%= f.email_field :email %>

		<h2><%= f.label "自己紹介(100文字まで)" %></h2>
		<%= f.text_area :introduction, class: 'js-text', size: "50x10" %>
		<a class="counter">0文字</a><a>/100文字</a>

		<div align="right"><%= f.submit "保存", class:"btn" %></div>

	</div>
</div>

<div align="right">
	<%= link_to "退会はこちら=>", users_unsubscribe_path %>
</div>


<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<%= render 'index', users: @users %>

<div class="paginate"><%= paginate @users %></div>

app/views/users/show.html.erb
<% if @user == current_user %>
  <h1>マイページ</h1>
<% else %>
  <h1><%= @user.name %></h1>
<% end %>

<div class="user-show">
  <%= attachment_image_tag @user, :profile_image, size:'300x300', fallback: "no_image_icon.jpg" %>
  <div class="user-show-content">
    <h2>名前</h2>
    <p><%= @user.name %></p><br>
    <h2>自己紹介</h2>
    <p><%= @user.introduction %></p><br>
    <p><i class="fas fa-pen"></i>総投稿数：<%= @user.post_items.count %>&emsp;
      <i class="fas fa-coins" style="color: yellow;"></i>獲得総Point：<%= @favorites_count %>
    </p><br>

    <p>
      <%= link_to "フォロー数#{@user.followings.count}", user_followings_path(@user) %>&emsp;
      <%= link_to "フォロワー数:#{@user.followers.count}", user_followers_path(@user) %>
    </p></br>

    <% if user_signed_in? %>
      <% if @user.id == current_user.id %>
        <h2>登録メールアドレス</h2>
        <p><%= @user.email %></p><br>
        <%= link_to "編集", edit_user_path(@user), class:"btn" %>
      <% else %>
        <div>
  	  		<% if current_user.following?(@user) %>
  	    		<%= link_to "フォロー中", user_relationships_path(@user.id), method: :delete, class: "btn" %>
  	  		<% else %>
  	    		<%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn" %>
  	  		<% end %>
	  		</div>
			<% end %>
    <% end %>
  </div>
</div>

<h2 class="user-post"><%= @user.name.truncate(20) %>さんの投稿 (全<%= @user.post_items.count %>件)</h2>
<div class="user-post-item">
	<% if @user.post_items.first %>
		<% @user.post_items.each do |post_item| %>
			<div class="user-post-item-content">
				<%= link_to post_item_path(post_item) do %>
					<%= attachment_image_tag post_item, :image, size:'200x300', fallback: "no_image.jpg" %>
					<h5><%= post_item.name.truncate(16) %></h5>
				<% end %>
			</div>
		<% end %>
	<% else %>
		<h3>投稿はありませんでした。</h3>
	<% end %>
</div>

app/views/users/thanks.html.erb
<div class="thanks-message">
  <h1>
    ご利用ありがとうございます。</br>
    またのご利用をお待ちしております。
  </h1>
  <div class="thanks-image"></div>
  <%= link_to "Topへ戻る", home_top_path %>
</div>

app/views/users/unsubscribe.html.erb
<div class="unsubscribe-form">
  <h1>本当に退会しますか？</h1>
  <div>
    <p>退会する場合は、『退会する』をクリックしてください。</p>
  </div>
  <div class="unsubscribe-image"></div>
  <div>
    <%= link_to '退会しない', user_path(@user), class:"btn" %>
    <%= link_to "退会する", users_withdraw_path(@user), method: :patch, class:"btn-danger" %>
  </div>
</div>