config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'home#start'
  get 'home/top' => 'home#top'
  get 'home/ranking' => 'home#ranking'

  get 'search/search'
  get '/search', to: 'search#search'

  get 'post_items/complete' => 'post_items#complete', as: 'post_items_complete'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'users_unsubscribe'
  patch 'users/:id/withdraw' => 'users#withdraw', as: 'users_withdraw'
  put 'users/:id/withdraw' => 'users#withdraw'
  get '/thanks' => 'users#thanks', as: 'thanks'


  resources :post_items do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :genres, only: [:create, :update, :destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def start
  end

  def top
    #本番環境でrandの表記を変更（mysqlだとrand,sqliteだとRANDOM)
    rand = Rails.env.production? ?  "rand()" : "RANDOM()"
    @post_items = PostItem.order(rand).limit(10) #post_itemをランダムで取得
    @new_post_items = PostItem.order("id DESC").limit(10) #post_itemを新しい順に取得
    @users = User.order(rand).limit(10) #userをランダムで取得
  end

  def ranking
    @post_items = PostItem.includes(:favorited_users).sort { |a, b| b.favorited_users.size <=> a.favorited_users.size }
    @users = User.includes(:post_items).sort { |a, b| b.post_items.size <=> a.post_items.size }
    @user_followers = User.includes(:followers).sort { |a, b| b.followers.size <=> a.followers.size }
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/ranking.html.erb
<h1>ランキング</h1>

<div class="wrap">
  <ul id="tab-menu">
    <li><a href="#tab1" class="active">Point数</a></li>
    <li><a href="#tab2" class="">投稿数</a></li>
    <li><a href="#tab3" class="">フォロワー数</a></li>
  </ul>

  <div id="tab-contents">
    <div id="tab1" class="tab">
      <% @post_items.first(7).each.with_index(1) do |post_item, i | %>
        <div class="tab-content">
          <p></p><h4>第<%= i %>位</h4>
          <%= link_to post_item_path(post_item) do %>
  					<%= attachment_image_tag post_item, :image, size:'200x300', fallback: "no_image.jpg" %>
  					<h5 align="center"><%= post_item.name.truncate(16) %></h5>
  				<% end %>
  				<h3 align="center">
					<i class="fas fa-coins" aria-hidden="true" style="color: yellow;"></i>
		    	<%= post_item.favorites.count %> points
		    	</h3>
        </div>
      <% end %>
    </div>

    <div id="tab2" class="tab">
	    <% @users.first(7).each.with_index(1) do |user, i | %>
        <div class="tab-user-content">
          <p></p><h4>第<%= i %>位</h4>
			    <%= link_to user_path(user) do %>
            <%= attachment_image_tag user, :profile_image, size:'250x250', fallback: "no_image_icon.jpg" %>
				    <h5 align="center"><%= user.name.truncate(16) %></h5>
			    <% end %>
          <h3 align="center">
					  <i class="fas fa-pen"></i>
		    	  <%= user.post_items.count %>件
		    	</h3>
		    </div>
	    <% end %>
    </div>

    <div id="tab3" class="tab">
	    <% @user_followers.first(7).each.with_index(1) do |user_follower, i | %>
        <div class="tab-user-content">
          <p></p><h4>第<%= i %>位</h4>
			    <%= link_to user_path(user_follower) do %>
            <%= attachment_image_tag user_follower, :profile_image, size:'250x250', fallback: "no_image_icon.jpg" %>
				    <h5 align="center"><%= user_follower.name.truncate(16) %></h5>
			    <% end %>
          <h3 align="center">
					  <i class="fas fa-user-friends"></i>
					  <%= user_follower.followers.count %>人
		    	</h3>
		    </div>
	    <% end %>
    </div>

  </div>

</div>

app/views/home/start.html.erb
<div class="start">
  <div class="start-1">
    <h1>
      ようこそ！！</br>
      Recommendersへ
    </h1>
    <div class="start-image"></div>
    <button class="btn1">Recommendersとは？</button><br><br>
    <button class="btn"><%= link_to "ログインする", new_user_session_path %></button>
    <button class="btn"><%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post %></button>
  </div>

  <div class="start-2 section">
    <div class="top-image1"></div>
    <div class="start-2-content">
      <h2>
        Recomendersとは?</br>
        Recommender（＝推薦人）となって、<br>
        おすすめの商品を投稿するサイトです。
      </h2>
      <h3>
        あなたがおすすめする商品やサービスを</br>
        あなたの文章で紹介しましょう！！
      </h3>
      <h3>
        概要を書くも良し、感想を書くも良し、</br>
        書き方はあなたの自由です。
      </h3>
      <p>※投稿には会員登録が必要です。</p><br>
      <button class="btn2">次へ</button>
    </div>
  </div>

  <div class="start-3 section">
    <div class="top-image2"></div>
    <div class="start-3-content">
      <h2>
        投稿を見て、</br>
        実際に商品を買った・利用したら、</br>
        投稿に対してPointを渡そう！！
      </h2>
      <h3>
        各投稿に対して1pointのPointを渡すことができます。</br>
        コメントも投稿可能ですので、</br>
        利用した感想などをコメントしましょう！！
      </h3>
      <p>※Point・コメントの投稿には会員登録が必要です。</p></br>
      <button class="btn3">次へ</button>
    </div>
  </div>

  <div class="start-4 section">
    <div class="top-image3"></div>
    <div class="start-4-content">
      <h2>どんどん投稿してPointを稼ごう！！</h2>
      <h3>
        他の人に「使ってみたい・利用しようかな」と</br>
        思わせるような文章を書くことがコツです。</br>
        但しネタバレは厳禁です。</br>
        あなたの素直な気持ちを文章で表現しましょう。
      </h3>
      <p>※Pointを稼ぐには会員登録が必要です。</p></br>
      <button class="btn4">次へ</button>
    </div>
  </div>

  <div class="start-5 section">
    <div class="top-image4"></div>
    <div class="start-5-content">
      <h2>もちろん投稿を見るだけでも大丈夫！！</h2>
      <h3>
        見たい映画がない、やりたいゲームがない、</br>
        そんな時は投稿を探してみましょう。</br>
        Recommender達が書いた投稿を読めば、</br>
        利用したくなる商品がきっと見つかるはずです。
      </h3>
      <p>※閲覧のみの場合、会員登録は不要です。</p></br>
      <button class="btn5">次へ</button>
    </div>
  </div>

  <div class="start-6 section">
    <h1>
      さあ、君もRecommenderになろう！！
    </h1>
      <button class="btn"><%= link_to '新規登録', new_user_registration_path %></button>
      <button class="btn"><%= link_to '登録せずに閲覧する', home_top_path %></button>
      <button class="btn"><%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post %></button>
  </div>
</div>

app/views/home/top.html.erb
<div id="top-slide">
  <div id="slide-image">
    <div class="image1"></div>
    <div class="image2"></div>
    <div class="image3"></div>
  </div>
</div>

<div class="top-slide">
  <h2>おすすめ投稿</h2></br>
  <div class="recommend-items">
    <% @post_items.each do |post_item| %>
      <div class="recommend-item">
      	<%= link_to post_item_path(post_item) do %>
      		<%= attachment_image_tag post_item, :image, size:'250x350', fallback: "no_image.jpg" %>
      		<h5><%= post_item.name.truncate(20) %></h5>
      	<% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="top-slide">
  <h2>新着投稿</h2></br>
  <div class="recommend-items">
    <% @new_post_items.each do |post_item| %>
      <div class="recommend-item">
      	<%= link_to post_item_path(post_item) do %>
      		<%= attachment_image_tag post_item, :image, size:'250x350', fallback: "no_image.jpg" %>
      		<h5><%= post_item.name.truncate(20) %></h5>
      	<% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="top-slide">
  <h2>おすすめユーザー</h2></br>
  <div class="recommend-users">
  	<% @users.each do |user| %>
  		<div class="recommend-user">
  			<%= link_to user_path(user) do %>
  				<%= attachment_image_tag user, :profile_image, size:'250x250', fallback: "no_image_icon.jpg" %>
  				<h5><%= user.name.truncate(18) %></h5>
  			<% end %>
  		</div>
  	<% end %>
  </div>
</div>