config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'home#start'
  get 'home/top' => 'home#top'
  get 'home/ranking' => 'home#ranking'

  get 'search/search'
  get '/search', to: 'search#search'

  get 'post_items/complete' => 'post_items#complete', as: 'post_items_complete'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'users_unsubscribe'
  patch 'users/:id/withdraw' => 'users#withdraw', as: 'users_withdraw'
  put 'users/:id/withdraw' => 'users#withdraw'
  get '/thanks' => 'users#thanks', as: 'thanks'


  resources :post_items do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :genres, only: [:create, :update, :destroy]
end

app/models/post_item.rb
class PostItem < ApplicationRecord

  validates :name, presence: true
  validates :introduction, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  validates :genre_id, presence: true

  belongs_to :user

  attachment :image
  belongs_to :genre

  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    PostItem.where('name LIKE ?', '%' + content + '%')
  end

end

app/controllers/post_items_controller.rb
class PostItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :complete]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]


  def index
    @genres = Genre.all
    if params[:genre_id]
      @genre = @genres.find(params[:genre_id])
      all_post_items = @genre.post_items.page(params[:page]).reverse_order
    else
      all_post_items = PostItem.page(params[:page]).reverse_order
    end
    @post_items = all_post_items.page(params[:page]).reverse_order
    @all_post_items_count = all_post_items.count
  end

  def show
    @post_item = PostItem.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = @post_item.post_comments.order(created_at: :desc).page(params[:page]).per(6)
    @user = @post_item.user
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @post_item = PostItem.new
    @genre = Genre.new
  end

  def create
    @post_item = PostItem.new(post_item_params)
    @post_item.user_id = current_user.id
    if @post_item.save
      redirect_to post_items_complete_path
    else
      @post_items = PostItem.all
      render 'new', alert: "投稿に失敗しました。"
    end
  end

  def edit
    @genres = Genre.all
    @post_item = PostItem.find(params[:id])
  end

  def update
    @post_item = PostItem.find(params[:id])
    if @post_item.update(post_item_params)
      redirect_to post_item_path(@post_item), notice: "変更を保存しました。"
    else
      render "edit", alert: "変更が保存できませんでした。"
    end
  end

  def destroy
    @post_item = PostItem.find(params[:id])
    @post_item.destroy
    redirect_to post_items_path, notice: "投稿を削除しました。"
  end

  def complete
    @genres = Genre.all
  end

  private

  def post_item_params
    params.require(:post_item).permit(:name, :introduction, :image, :genre_id)
  end

  def ensure_correct_user
    @post_item = PostItem.find(params[:id])
    unless @post_item.user == current_user
      redirect_to user_path(current_user), alert: "権限がございません。"
    end
  end

end

app/helpers/post_items_helper.rb
module PostItemsHelper
end

app/views/post_items/_search_index.html.erb
<div class="search-item-content">
	<div class="search-item">
		<% post_items.each do |post_item| %>
			<%= link_to post_item_path(post_item) do %>
				<%= attachment_image_tag post_item, :image, size:'200x300', fallback: "no_image.jpg" %>
				<h5><%= post_item.name.truncate(16) %></h5>
				<i class="fa fa-comment"></i>
	  		<%= post_item.post_comments.count %>
				<i class="fas fa-coins" aria-hidden="true" style="color: yellow;"></i>
	    	<%= post_item.favorites.count %> point
			<% end %>
		<% end %>
	</div>
</div>

app/views/post_items/complete.html.erb
<div class="complete">
  <h1>投稿ありがとうございます！！</h1>
  <div class="complete-image"></div>
  <%= link_to "Topへ戻る", home_top_path %>
</div>

app/views/post_items/edit.html.erb
<h1>投稿編集</h1>

<%= form_with model:@post_item, local:true do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
  <div class="post-item-edit">
  	<div class="post-item-edit-image">
    	<h2><%= f.label :image, "イメージ画像" %></h2>
    	<%= attachment_image_tag @post_item, :image, id: "img_prev", size:'400x500', fallback: "no_image.jpg" %></br>
    	<%= f.attachment_field :image %>
    </div>

    <div class="post-item-edit-form">
      <h2><%= f.label :name, "タイトル" %></h2>
      <%= f.text_field :name %>

      <h2><%= f.label :introduction, "紹介文(140文字まで)" %></h2>
      <%= f.text_area :introduction, class: 'js-text', size: "50x15" %>
      <p class="counter">0文字</p>

      <h2><%= f.label :genre_id, "カテゴリー" %></h2>
      <%= f.collection_select :genre_id, Genre.all, :id, :name %>

      <div class="save-btn"><%= f.submit "保存", class:"btn" %></div>
    </div>
  </div>
<% end %>

<div align="right">
  <%= link_to "保存せずに戻る", post_item_path(@post_item) %>
  </div>

app/views/post_items/index.html.erb
<h1>投稿一覧</h1>

<% if user_signed_in? %>
	<div class="post-btn">
		<%= link_to new_post_item_path do %>
			<i class="fas fa-pen">投稿</i>
		<% end %>
	</div>
<% end %>



<div class="post-item-index">
	<div class="genre-sidebar">
		<h3>カテゴリー</h3>
		<% @genres.each do |genre| %>
			<%= link_to genre.name, post_items_path(genre_id: genre.id) %>
		<% end %>
	</div>

	<div class="post-item-content">
		<% if params[:genre_id] %>
			<h2><%= @genre.name %>の商品一覧 (全<%= @all_post_items_count %>件)</h2>
		<% else %>
			<h2>商品一覧 (全<%= @all_post_items_count %>件)</h2>
		<% end %>
		<div class="post-item">
			<% if @post_items.first %>
				<% @post_items.each do |post_item| %>
					<%= link_to post_item_path(post_item) do %>
						<%= attachment_image_tag post_item, :image, size:'200x300', fallback: "no_image.jpg" %>
						<h5><%= post_item.name.truncate(16) %></h5>
						<i class="fa fa-comment"></i>
			  		<%= post_item.post_comments.count %>
						<i class="fas fa-coins" style="color: yellow;"></i>
			    	<%= post_item.favorites.count %> point
					<% end %>
				<% end %>
			<% else %>
				<h3>対応する商品はありませんでした。</h3>
			<% end %>
		</div>
		<div class="paginate"><%= paginate @post_items %></div>
	</div>
</div>

app/views/post_items/new.html.erb
<h1>新規投稿</h1>

<%= form_with model:@post_item, local:true do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
  <div class="post-item-new">
  	<div class="post-item-new-image">
    	<h2><%= f.label :image, "イメージ画像" %></h2>
    	<%= attachment_image_tag @post_item, :image, id: "img_prev", size:'400x500', fallback: "no_image.jpg" %></br>
    	<%= f.attachment_field :image %>
    </div>

    <div class="post-item-new-form">
      <h2><%= f.label :name %></h2>
      <%= f.text_field :name %>

      <h2><%= f.label :introduction %></h2>
      <%= f.text_area :introduction, class: 'js-text', size: "50x15", placeholder: "ネタバレはお控えください。140文字まで入力が可能です。" %>
      <a class="counter">0文字</a><a>/140文字</a>

      <h2><%= f.label :genre_id, "カテゴリー" %></h2>
      <%= f.collection_select :genre_id, Genre.all, :id, :name %></br></br></br>
      <p>※カテゴリーがない場合は下記より追加してください。</p>

      <%= f.submit "投稿", class:"btn" %>
    </div>
  </div>
<% end %>

<div align="right">
  <%= link_to "投稿せずに戻る", post_items_path %>
</div>

<div class="genre-form">
  <h2>カテゴリーの登録</h2>
  <%= form_with model:@genre, local:true do |f| %>
  	<%= f.text_field :name %>
  	<%= f.submit "追加する", class:"btn" %>
  <% end %>
</div>

app/views/post_items/show.html.erb
<h1>投稿詳細</h1>

<div class="post-item-show">
	<%= attachment_image_tag @post_item, :image, size:'400x500', fallback: "no_image.jpg" %>
	<div class="post-item-recommend">
		<h2>タイトル</h2>
		<p><%= @post_item.name %></p></br>
		<h2>紹介文</h2>
		<p><%= @post_item.introduction %></p></br>
		<h2>カテゴリー</h2>
		<p><%= @post_item.genre.name %></p></br>
		<h2>投稿者</h2>
		<p><%= link_to @post_item.user.name, user_path(@post_item.user) %></p></br>

		<div>
			<% if user_signed_in? %>
				<% if current_user != @user %>
		  		<% if current_user.following?(@user) %>
		    		<%= link_to "フォロー中", user_relationships_path(@user.id), method: :delete, class: "btn" %>
		  		<% else %>
		    		<%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn" %>
		  		<% end %>
				<% end %>
			<% end %>
		</div></br>

		<div class="post-item-icons">
			<div id="comment-count_<%= @post_item.id %>">
				<%= render "post_comments/count", post_item: @post_item %>
			</div>

			<% if user_signed_in? %>
				<div id='favorite-btn_<%= @post_item.id %>'>
					<%= render "favorites/favorite-btn", post_item: @post_item %>
				</div>
			<% else %>
				<div>
					<i class="fas fa-coins" aria-hidden="true" style="color: yellow;"></i>
					<%= @post_item.favorites.count %> point
				</div>
			<% end %>
		</div><br>



		<% if @post_item.user == current_user %>
			<%= link_to "編集", edit_post_item_path(@post_item), class: 'btn' %>
			<%= link_to "削除", post_item_path(@post_item), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: 'btn-danger' %>
		<% end %>
	</div>
</div>


<h2 class="comment-title">コメント</h2>
<div class="post-comment">

	<div id="comment-index">
		<%= render "post_comments/index", post_comments: @post_comments %><br>
		<%= link_to_next_page @post_comments, 'もっと見る', remote: true, class: 'more-link', id: 'more-link' %>
	</div>


	<% if user_signed_in? %>
		<%= form_with model:[@post_item, @post_comment], remote: true do |f| %>
	  <div class="comment-form">
	  	<%= f.text_area :comment, size:"60x5", placeholder: "コメントをここに。100文字までコメントが可能です。" %>
	  	<div align="right"><%= f.submit "コメント", class:"btn" %></div>
	  </div>
		<% end %>
	<% else %>
		<p>　　※コメントには登録が必要です</p>
	<% end %>
</div>

app/views/post_items/show.js.erb
$('#comment-index').append("<%= j(render 'post_comments/index', object: @post_comments) %>")
$("#more-link").replaceWith("<%= j(link_to_next_page(@post_comments, 'もっと見る', remote: true, class: 'more-link', id: 'more-link')) %>");