config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'home#start'
  get 'home/top' => 'home#top'
  get 'home/ranking' => 'home#ranking'

  get 'search/search'
  get '/search', to: 'search#search'

  get 'post_items/complete' => 'post_items#complete', as: 'post_items_complete'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'users_unsubscribe'
  patch 'users/:id/withdraw' => 'users#withdraw', as: 'users_withdraw'
  put 'users/:id/withdraw' => 'users#withdraw'
  get '/thanks' => 'users#thanks', as: 'thanks'


  resources :post_items do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :genres, only: [:create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post_item


end

app/models/genre.rb
class Genre < ApplicationRecord

  validates :name, presence: true, uniqueness: true

  has_many :post_items, dependent: :destroy

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  validates :comment, presence: true, length: { maximum: 100 }


  belongs_to :user
  belongs_to :post_item


end

app/models/post_item.rb
class PostItem < ApplicationRecord

  validates :name, presence: true
  validates :introduction, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  validates :genre_id, presence: true

  belongs_to :user

  attachment :image
  belongs_to :genre

  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    PostItem.where('name LIKE ?', '%' + content + '%')
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :introduction, length: { maximum: 100 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_items, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorites_post_items, through: :favorites, source: :post_item
  attachment :profile_image

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  scope :only_valid, -> { where(is_valid: true) }

  enum is_valid: {"有効": true, "無効": false}

  def active_for_authentication?
    super && (self.is_valid === "有効")
  end

  def self.search_for(content, method)
    User.where('name LIKE ?', '%' + content + '%')
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.guest
    find_or_create_by!(name: 'ゲスト', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end


end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to new_post_item_path, notice: "カテゴリーを追加しました。"
    else
      redirect_to new_post_item_path, alert: "カテゴリーの追加に失敗しました。"
    end
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to genres_path, notice: "変更が保存されました。"
    else
      render :edit, alert: "変更が保存できませんでした。"
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path, notice: "カテゴリーを削除しました。"
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def start
  end

  def top
    #本番環境でrandの表記を変更（mysqlだとrand,sqliteだとRANDOM)
    rand = Rails.env.production? ?  "rand()" : "RANDOM()"
    @post_items = PostItem.order(rand).limit(10) #post_itemをランダムで取得
    @new_post_items = PostItem.order("id DESC").limit(10) #post_itemを新しい順に取得
    @users = User.order(rand).limit(10) #userをランダムで取得
  end

  def ranking
    @post_items = PostItem.includes(:favorited_users).sort { |a, b| b.favorited_users.size <=> a.favorited_users.size }
    @users = User.includes(:post_items).sort { |a, b| b.post_items.size <=> a.post_items.size }
    @user_followers = User.includes(:followers).sort { |a, b| b.followers.size <=> a.followers.size }
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def search
		@genres = Genre.all
		@model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'user'
			@records = User.search_for(@content, @method)
		else
			@records = PostItem.search_for(@content, @method)
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :unsubscribe, :withdraw]
  before_action :ensure_correct_user, only: [:edit, :update, :unsubscribe, :withdraw]

  def index
    @users = User.only_valid.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @favorites_count = 0
    @user.post_items.each do |post_item|
      @favorites_count += post_item.favorites.count
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: '会員情報の更新が完了しました。'
    else
      render :edit, alert: '会員情報の更新に失敗しました。'
    end
  end

  def unsubscribe
    @user = current_user
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.post_items.delete_all
    @user.post_comments.delete_all
    @user.update(is_valid: "無効")
    reset_session
    redirect_to thanks_path, notice: 'ご利用ありがとうございました。'
  end

  def thanks
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user), alert: "権限がございません。"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_items_helper.rb
module PostItemsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h3>
      <%= model.errors.count %>件のエラーが発生しました。</br>
      以下ご確認お願いいたします。
    </h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li>・<%= message %></li>
      <% end %>
    </ul>
  </div></br>
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <header>
    <h1 class="header-title">
      <%= link_to home_top_path do %>
        <%= image_tag 'logo1.jpg' %>
      <% end %>
    </h1>
    <nav class="pc-header-nav">
      <ul class="header-item">
        <li>ようこそ!! <%= current_user.name %>さん</li>
        <li><i class="fas fa-crown"></i><%= link_to 'ランキング', home_ranking_path %></li>
        <li class="dropdown">
          <i class="fas fa-list"></i><%= link_to '投稿一覧▼', post_items_path %>
            <ul class="dropdown-menu">
              <li><%= link_to '全ての投稿', post_items_path %></li>
              <% genres = Genre.all %>
              <% genres.each do |genre| %>
              <li>・<%= link_to genre.name, post_items_path(genre_id: genre.id) %></li>
              <% end %>
            </ul>
        </li>
        <li><i class="fas fa-users"></i><%= link_to 'ユーザー', users_path %></li>
        <li><i class="fas fa-user"></i><%= link_to 'マイページ', user_path(current_user.id) %></li>
        <li><i class="fas fa-sign-out-alt"></i><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      </ul>
    </nav>
<%# スマホ用のメニュー %>
    <div id="sp-menu">
      <ul>
        <li>ようこそ!! <%= current_user.name %>さん</li>
        <li><i class="fas fa-crown"></i><%= link_to 'ランキング', home_ranking_path %></li>
        <li><i class="fas fa-list"></i><%= link_to '投稿一覧', post_items_path %></li>
        <li><i class="fas fa-users"></i><%= link_to 'ユーザー', users_path %></li>
        <li><i class="fas fa-user"></i><%= link_to 'マイページ', user_path(current_user.id) %></li>
        <li><i class="fas fa-sign-out-alt"></i><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>

    <div id="hm-icon">
      <a class="menu-trigger" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>

  </header>
  <% else %>
  <header>
      <h1 class="header-title">
        <%= link_to home_top_path do %>
          <%= image_tag 'logo1.jpg' %>
        <% end %>
      </h1>
      <nav class="pc-header-nav">
        <ul class="header-item">
          <li><i class="fas fa-crown"></i><%= link_to 'ランキング', home_ranking_path %></li>
          <li class="dropdown">
            <i class="fas fa-list"></i><%= link_to '投稿一覧', post_items_path %>
            <ul class="dropdown-menu">
              <li><%= link_to '全ての投稿', post_items_path %></li>
              <% genres = Genre.all %>
              <% genres.each do |genre| %>
              <li>・<%= link_to genre.name, post_items_path(genre_id: genre.id) %></li>
              <% end %>
            </ul>
          </li>
          <li><i class="fas fa-users"></i><%= link_to 'ユーザー', users_path %></li>
          <li><i class="fas fa-user-plus"></i><%= link_to '新規登録', new_user_registration_path %></li>
          <li><i class="fas fa-sign-in-alt"></i><%= link_to 'ログイン', new_user_session_path %></li>
        </ul>
      </nav>
<%# スマホ用のメニュー %>

      <div id="sp-menu">
        <ul>
          <li><i class="fas fa-crown"></i><%= link_to 'ランキング', home_ranking_path %></li>
          <li><i class="fas fa-list"></i><%= link_to '投稿一覧', post_items_path %></li>
          <li><i class="fas fa-users"></i><%= link_to 'ユーザー', users_path %></li>
          <li><i class="fas fa-user-plus"></i><%= link_to '新規登録', new_user_registration_path %></li>
          <li><i class="fas fa-sign-in-alt"></i><%= link_to 'ログイン', new_user_session_path %></li>
        </ul>
      </div>

      <div id="hm-icon">
        <a class="menu-trigger" href="#">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>

  </header>
<% end %>

app/views/layouts/_notice.html.erb
<% if notice %>
  <div class="alert alert-info">
    <%= notice %>
  </div>
<% elsif alert %>
  <div class="alert alert-danger">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%# ↓レスポンシブ対応のため一文追加  %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Recommenders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <script src="https://kit.fontawesome.com/639d4d1d29.js" crossorigin="anonymous"></script>

  </head>

  <body>
    <div id="contents">
      <% unless current_page?(root_path) %>
        <%= render 'layouts/header' %>
      <% end %>

      <main>
        <% unless current_page?(root_path) %>
          <%= render 'search/search_form' %>
        <% end %>
        <%= render 'layouts/notice' %>
        <%= yield %>
      </main>

      <footer>
        <p class="copy-right">© All rights reserved by ryota.</p>
      </footer>

<%# トップへ戻るボタン %> 
      <span id="page_top">
        <a href="#">
        </a>
      </span>

    </div>
  </body>
</html>